<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="nafrinhp" failures="5" tests="11" name="executinginchrome" time="63.061" errors="0" timestamp="2024-11-20T20:31:41 IST">
  <testcase classname="com.sevenrmartsupermart.tests.LoginTest" name="checkGroceryAppName" time="0.18"/>
  <testcase classname="com.sevenrmartsupermart.tests.LoginTest" name="verifyAdminUserLogin" time="0.962"/>
  <testcase classname="com.sevenrmartsupermart.tests.LoginTest" name="verifyAlertMessageIsShownWithWrongPassword" time="0.855"/>
  <testcase classname="com.sevenrmartsupermart.tests.LoginTest" name="verifyAlertMessageIsShownWithWrongUsername" time="0.675"/>
  <testcase classname="com.sevenrmartsupermart.tests.LoginTest" name="verifyAlertMessageIsShownWithWrongUsernameAndPassword" time="2.258"/>
  <testcase classname="com.sevenrmartsupermart.tests.LoginTest" name="verifyCSSAttributesofSignInButton" time="0.118">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [16px 16px] but found [16px]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [16px 16px] but found [16px]
at com.sevenrmartsupermart.tests.LoginTest.verifyCSSAttributesofSignInButton(LoginTest.java:133)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- verifyCSSAttributesofSignInButton -->
  <testcase classname="com.sevenrmartsupermart.tests.LoginTest" name="verifyLoginDetailsAreSavedAfterClickingRememberMeCheckBox" time="2.736">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [16px 16px] but found [16px]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [16px 16px] but found [16px]
at com.sevenrmartsupermart.tests.LoginTest.verifyLoginDetailsAreSavedAfterClickingRememberMeCheckBox(LoginTest.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginDetailsAreSavedAfterClickingRememberMeCheckBox -->
  <testcase classname="com.sevenrmartsupermart.tests.LoginTest" name="verifyLoginIsAllowedUsingEnterKeyInKeyboard" time="1.861"/>
  <testcase classname="com.sevenrmartsupermart.tests.LoginTest" name="verifyLoginIsNotAllowedWithoutPassword" time="0.724">
    <failure type="java.lang.AssertionError" message="Login is not allowed expected [Login|7rmart supermarket] but found [Login | 7rmart supermarket]">
      <![CDATA[java.lang.AssertionError: Login is not allowed expected [Login|7rmart supermarket] but found [Login | 7rmart supermarket]
at com.sevenrmartsupermart.tests.LoginTest.verifyLoginIsNotAllowedWithoutPassword(LoginTest.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginIsNotAllowedWithoutPassword -->
  <testcase classname="com.sevenrmartsupermart.tests.LoginTest" name="verifyLoginIsNotAllowedWithoutUsername" time="0.368">
    <failure type="java.lang.AssertionError" message="Login is not allowed expected [Login|7rmart supermarket] but found [Login | 7rmart supermarket]">
      <![CDATA[java.lang.AssertionError: Login is not allowed expected [Login|7rmart supermarket] but found [Login | 7rmart supermarket]
at com.sevenrmartsupermart.tests.LoginTest.verifyLoginIsNotAllowedWithoutUsername(LoginTest.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginIsNotAllowedWithoutUsername -->
  <testcase classname="com.sevenrmartsupermart.tests.LoginTest" name="verifyRememberMeCheckboxIsEnabled" time="0.51">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.sevenrmartsupermart.tests.LoginTest.verifyRememberMeCheckboxIsEnabled(LoginTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyRememberMeCheckboxIsEnabled -->
</testsuite> <!-- executinginchrome -->
